### ISSUE TITLE
Text input cursor jumps to end when inserting/removing character within the string

### ISSUE THREAD

**Issue by pieterdd** [lapce/floem#282] opened 2024-01-21 10:07 UTC
https://github.com/lapce/floem/assets/1407980/cddb5665-e852-451f-aef0-084f44b6af04

This line appears to trigger, causing the cursor glyph index to jump to the end of the line:
https://github.com/lapce/floem/blob/main/src/views/text_input.rs#L948

Something in 189985f459f1533399e1b5e26cf95f63ea19dbb9 appears to have triggered a bit of regression.

**Comment by presiyan-ivanov** [comment] 2024-01-22 10:46
I am working on something else at the moment - password input, and I had to improve the way input's state is handled(split it into separate messages for focus, text update, etc), and I seem to have fixed this issue on my local without even knowing about it :D

**Comment by jrmoulton** [comment] 2024-01-22 17:46
Tested presiyan-ivanov changes and can those changes fixed it for me

**Comment by timboudreau** [comment] 2024-05-22 22:27
I wonder if this is what causes the rare, but maddening, issue where I'm inserting into some code, and suddenly a bunch of lines below the caret become selected and get deleted on the next character typed.  I hadn't found a way to reliably reproduce it, and it's only a few times a day, but it sounds like it could be caused by this.

**Comment by sgued** [comment] 2024-08-11 11:10
This is the same issue as https://github.com/lapce/floem/issues/532, should be fixed by https://github.com/lapce/floem/pull/548

**Closed** 2024-11-04 09:04 UTC
